### ISSUE TITLE
Buffer::allocate should be unsafe

### ISSUE THREAD

**Issue by nox** [sagebind/chttp#1]
It is undefined behaviour to read any uninitialised value, even if that value is a byte. Therefore, a function returning an uninitialised slice should be unsafe.

**Comment by sagebind** [comment]
I'm not sure I agree, though I could be missing something. `u8` has the exact representation of a byte. Therefore, even though the memory is not initialized by Rust, all regions of memory are always initialized with "bytes", though the initial contents after allocating are undefined. So even though the array is filled with possibly random, undefined values, the all such values are still legal for `u8`.

**Comment by nox** [comment]
It doesn't matter, one should not, *under any circumstance*, be able to read uninitialised memory from safe code.

**Comment by nox** [comment]
https://doc.rust-lang.org/beta/reference/behavior-considered-undefined.html

> Reads of undef (uninitialized) memory.
