### ISSUE TITLE
Expose client TLS certificate settings

### ISSUE THREAD

**Issue by tazjin** [sagebind/chttp#19]
Follow-up from [this Reddit thread](https://www.reddit.com/r/rust/comments/athkan/any_alternative_to_reqwest_in_rust/eh3yftj/?context=3).

----------

`libcurl` exposes settings for using TLS certificates presented by the client when initiating a TLS connection. This is used for so-called certificate-based authentication.

In `curl` (the CLI tool) these settings are controlled by the `--cert` / `--key` and `--cert-type` / `--key-type` flags. In the Rust bindings to `libcurl`, these correspond to [`Easy2::ssl_cert`](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy2.html#method.ssl_cert), [`Easy2::ssl_key`](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy2.html#method.ssl_key) and the `_type` methods.

It would be very useful to have those exposed in `cHTTP` in some way!

**Comment by sagebind** [comment]
This will be included in the 0.4.1 release.
